/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicIdImport } from './routes/$publicId'
import { Route as IndexImport } from './routes/index'
import { Route as PreviewPublicIdImport } from './routes/preview.$publicId'

// Create/Update Routes

const PublicIdRoute = PublicIdImport.update({
  id: '/$publicId',
  path: '/$publicId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PreviewPublicIdRoute = PreviewPublicIdImport.update({
  id: '/preview/$publicId',
  path: '/preview/$publicId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$publicId': {
      id: '/$publicId'
      path: '/$publicId'
      fullPath: '/$publicId'
      preLoaderRoute: typeof PublicIdImport
      parentRoute: typeof rootRoute
    }
    '/preview/$publicId': {
      id: '/preview/$publicId'
      path: '/preview/$publicId'
      fullPath: '/preview/$publicId'
      preLoaderRoute: typeof PreviewPublicIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$publicId': typeof PublicIdRoute
  '/preview/$publicId': typeof PreviewPublicIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$publicId': typeof PublicIdRoute
  '/preview/$publicId': typeof PreviewPublicIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$publicId': typeof PublicIdRoute
  '/preview/$publicId': typeof PreviewPublicIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$publicId' | '/preview/$publicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$publicId' | '/preview/$publicId'
  id: '__root__' | '/' | '/$publicId' | '/preview/$publicId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicIdRoute: typeof PublicIdRoute
  PreviewPublicIdRoute: typeof PreviewPublicIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicIdRoute: PublicIdRoute,
  PreviewPublicIdRoute: PreviewPublicIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$publicId",
        "/preview/$publicId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$publicId": {
      "filePath": "$publicId.tsx"
    },
    "/preview/$publicId": {
      "filePath": "preview.$publicId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
